"""added_unquie_constraint

Revision ID: 440241328372
Revises: 59e15b0664cc
Create Date: 2024-10-11 23:50:51.444923

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "440241328372"
down_revision: Union[str, None] = "59e15b0664cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["username"])
    op.create_unique_constraint(None, "user", ["phone"])
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
