"""added_fileds_for_player

Revision ID: c50362b608b4
Revises: 440241328372
Create Date: 2024-10-12 00:43:22.850389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50362b608b4'
down_revision: Union[str, None] = '440241328372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('weight', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('games', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'games')
    op.drop_column('player', 'weight')
    op.drop_column('player', 'height')
    # ### end Alembic commands ###
